---
title: "Consumer Financial Protection Bureau complaints from March-January 2021"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(data.table)
library(dplyr)
library(kableExtra)
library(tidyr)
library(flexdashboard)
library(tidyverse)
library(lubridate)
library(janitor)
library(readxl)
library(writexl)

complaints <- readRDS("complaints.rds")
```

Column {data-width=350}
-----------------------------------------------------------------------



```{r}
most_complaints <- complaints %>%
  count(company, sort = TRUE)
  
d1 = head(most_complaints, 10)

kable(d1,
      caption = "Top 10 Companies with the Most Complaints"
      )
```

Column {data-width=650}
-----------------------------------------------------------------------


```{r}

date_of_complaints <- complaints %>%
  count(mm_yy_sent_to_company, sort = TRUE)

ggplot(date_of_complaints, aes(x = mm_yy_sent_to_company, y = n)) + 
  geom_col(color = "#9ebcda", fill = "#9ebcda") +
  coord_flip() +
  scale_y_continuous(name = "Number of Complaints", labels = scales::comma) +
  scale_x_discrete(name = "Date") +
  labs(title = "Consumer Complaints", 
       subtitle = "March 2020-January 2021",
       caption = "Source: Consumer Financial Protection Bureau")
```

Column {data-width=650}
-----------------------------------------------------------------------
```{r}
most_issues <- complaints %>%
  count(issue, sort = TRUE)

d2 = head(most_issues, 10)

kable(d2,
      caption = "Top 10 Most Reported Issues",)
```


```{r}
state <- complaints %>%
  count(state, sort = TRUE)

d3 = head(state, 20)

ggplot(d3, aes(x = state, y = n)) + 
  geom_col(color = "#9ebcda", fill = "#9ebcda") +
  coord_flip() +
  scale_y_continuous(name = "Number of Complaints", labels = scales::comma) +
  scale_x_discrete(name = "State") +
  labs(title = "Consumer Complaints by Top 20 States", 
       subtitle = "March 2020-January 2021",
       caption = "Source: Consumer Financial Protection Bureau")
```

